// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MediPulses.DAL.Context;

#nullable disable

namespace MediPulses.DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260411205417_CreateMasterDataTables")]
    partial class CreateMasterDataTables
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MediPulses.DAL.Entities.Facility", b =>
                {
                    b.Property<int>("FacilityID").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilityID"));
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Region").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("Type").HasColumnType("int");
                    b.HasKey("FacilityID");
                    b.ToTable("Facilities");
                });

            modelBuilder.Entity("MediPulses.DAL.Entities.StorageZone", b =>
                {
                    b.Property<int>("ZoneID").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ZoneID"));
                    b.Property<int>("Capacity").HasColumnType("int");
                    b.Property<int>("FacilityID").HasColumnType("int");
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<int>("TemperatureProfile").HasColumnType("int");
                    b.HasKey("ZoneID");
                    b.HasIndex("FacilityID");
                    b.ToTable("StorageZones");
                });

            modelBuilder.Entity("MediPulses.DAL.Entities.Supplier", b =>
                {
                    b.Property<int>("SupplierID").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SupplierID"));
                    b.Property<string>("Name").IsRequired().HasMaxLength(50).HasColumnType("nvarchar(50)");
                    b.Property<string>("Status").IsRequired().HasMaxLength(20).HasColumnType("nvarchar(20)");
                    b.Property<int>("SupplierType").HasColumnType("int");
                    b.HasKey("SupplierID");
                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("MediPulses.DAL.Entities.User", b =>
                {
                    b.Property<int>("UserID").ValueGeneratedOnAdd().HasColumnType("int");
                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));
                    b.Property<string>("Email").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Name").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Password").IsRequired().HasColumnType("nvarchar(max)");
                    b.Property<string>("Phone").HasColumnType("nvarchar(max)");
                    b.Property<string>("Role").HasColumnType("nvarchar(max)");
                    b.HasKey("UserID");
                    b.ToTable("User");
                });

            modelBuilder.Entity("MediPulses.DAL.Entities.StorageZone", b =>
                {
                    b.HasOne("MediPulses.DAL.Entities.Facility", "Facility")
                        .WithMany("StorageZones")
                        .HasForeignKey("FacilityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Facility");
                });

            modelBuilder.Entity("MediPulses.DAL.Entities.Facility", b =>
                {
                    b.Navigation("StorageZones");
                });
#pragma warning restore 612, 618
        }
    }
}
